### PR TITLE
change for rooms to work

### PR DESCRIPTION
**Pull request by tommytee**
edit needed for rooms to work.  
I am using with updated socket.io-p2p https://github.com/socketio/socket.io-p2p/pull/36

### CODE REVIEW

**Comment by rogual** [comment]
@tommytee You've moved your head branch so this PR now has extra stuff in it. (The first commit works though — thank you!)

**Comment by tommytee** [comment]
Thanks.
I removed that commit from the PR.

**Review by swiftmas — APPROVED** [review]
This really needs to be added.

**Comment by runemadsen** [comment]
+1

**Pull request merged**
